name: auto-aur-update
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"


jobs:
  # This workflow contains a single job called "build"



  UpdatePkg:
    strategy:
      fail-fast: false
      matrix:
        PKGBUILDs:
        - aionui-bin
        - mrrss-appimage
        - orca-note-appimage
        - any-code-appimage

    runs-on: ubuntu-latest
#    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start


    steps:
      - uses: actions/checkout@v2
      - uses: ./build-aur-action
        with:
          pkgname: ${{ matrix.PKGBUILDs }}
          pkgdir: ${{ matrix.PKGBUILDs }}

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@master
        with:
          pkgname: ${{ matrix.PKGBUILDs }}
          pkgbuild: ${{ matrix.PKGBUILDs }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
          allow_empty_commits: false
          updpkgsums: true

  Task:
    needs: UpdatePkg
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Make Time log
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log

    - name: Commit and Push
      run: |
        git config --local user.email 1304024859@qq.com
        git config --local user.name zzy-ac
        git add time.log
        git commit -m "update new time.log" || exit 0
        git pull --rebase origin main
        git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
